# Generated by Django 4.1.2 on 2023-09-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_alter_comment_room_delete_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='room',
            new_name='blog',
        ),
    ]
