# Generated by Django 4.1.2 on 2023-04-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
