# Generated by Django 4.1.2 on 2023-03-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GetJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('UserName', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('education', models.CharField(max_length=120)),
                ('qualification', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('your_skils', models.CharField(max_length=120)),
                ('ever_worked', models.CharField(max_length=120)),
                ('jobrole', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
                ('describe', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_name', models.CharField(max_length=120)),
                ('soft_type', models.CharField(max_length=120)),
                ('soft_time', models.CharField(max_length=120)),
                ('soft_amount', models.CharField(max_length=120)),
                ('soft_desc', models.CharField(max_length=120)),
            ],
        ),
    ]
