# Generated by Django 4.1.2 on 2023-03-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_getjob_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getjob',
            old_name='your_skils',
            new_name='your_skills',
        ),
        migrations.RemoveField(
            model_name='home',
            name='education',
        ),
        migrations.RemoveField(
            model_name='home',
            name='qualification',
        ),
    ]
