# Generated by Django 4.1.2 on 2023-04-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_your_skils_getjob_your_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getjob',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
