# Generated by Django 4.1.2 on 2023-08-11 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_software_alter_order_soft_desc_alter_order_soft_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='soft_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
