# Generated by Django 4.1.2 on 2023-08-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_order_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='soft_type',
        ),
    ]
