# Generated by Django 4.1.2 on 2023-08-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_order_soft_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Software',
            new_name='Softwares',
        ),
    ]
