# Generated by Django 4.1.2 on 2023-08-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_softwaretype_rename_softwarename_softwares_software_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='soft_type',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='software',
        ),
        migrations.AddField(
            model_name='softwares',
            name='names',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='SoftwareType',
        ),
    ]
