# Generated by Django 4.1.2 on 2023-08-13 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_softwaretype'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='soft_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.softwaretype'),
        ),
    ]
