# Generated by Django 4.1.2 on 2023-08-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_order_soft_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwares',
            name='names',
            field=models.CharField(max_length=200),
        ),
    ]
