# Generated by Django 4.1.2 on 2023-08-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_softwares_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwaretype',
            old_name='software_type',
            new_name='name',
        ),
    ]
