# Generated by Django 4.1.2 on 2023-08-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_software_type_softwaretype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwaretype',
            old_name='name',
            new_name='softName',
        ),
    ]
