# Generated by Django 4.1.2 on 2023-08-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_name_softwaretype_softname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getjob',
            name='qualification',
            field=models.DateTimeField(max_length=120),
        ),
    ]
