# Generated by Django 4.1.2 on 2023-08-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_getjob_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getjob',
            name='qualification',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='soft_time',
            field=models.DateTimeField(max_length=120),
        ),
    ]
