# Generated by Django 4.1.2 on 2023-09-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_order_soft_time_remove_order_soft_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='soft_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
